### PR TITLE
fix(docker): adding bash to support SCT for Scylla enterprice

### PR DESCRIPTION
**Pull request by CodeLieutenant**

### CODE REVIEW

**Review by fruch — APPROVED** [review]

**Comment by fruch** [comment]
@CodeLieutenant 

I think tagging this would to get it into SCT and confirm it's fixing the issue.

**Comment by CodeLieutenant** [comment]
> @CodeLieutenant
> 
> I think tagging this would to get it into SCT and confirm it's fixing the issue.

It will not do it automatically as c-s image is bound to 3.12.1 and tagging it to 3.12.2 will not pull, I'm not sure if it's a good idea to point SCT image to :latest as sometimes, c-s, can be broken.

Retagging it to 3.12.1 would require deleting the tag from docker hub (for which I don't think to have permissions)

@fruch would it be better to change SCT to v3.12.2, or go thru like described?

**Comment by fruch** [comment]
> > @CodeLieutenant
> > I think tagging this would to get it into SCT and confirm it's fixing the issue.
> 
> It will not do it automatically as c-s image is bound to 3.12.1 and tagging it to 3.12.2 will not pull, I'm not sure if it's a good idea to point SCT image to :latest as sometimes, c-s, can be broken.
> 
> Retagging it to 3.12.1 would require deleting the tag from docker hub (for which I don't think to have permissions)
> 
> @fruch would it be better to change SCT to v3.12.2, or go thru like described?

yes, but it wasn't yet created

**Comment by CodeLieutenant** [comment]
> yes, but it wasn't yet created
Sorry, I pushed to my fork and not to this one... Should be up in a couple of minutes

**Pull request merged**
